'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import styles from '../partner.module.css'

const labels={pending:'승인 대기',approved:'승인 완료',rejected:'승인 거절',suspended:'제휴 중지'}
export default function PartnerPending(){const [profile,setProfile]=useState(null);const [loading,setLoading]=useState(true);const router=useRouter();useEffect(()=>{const load=async()=>{const {data:userData}=await supabase.auth.getUser();if(!userData.user){router.replace('/partner/login');return}const {data}=await supabase.from('partner_profiles').select('business_name,email,status,rejected_reason').eq('user_id',userData.user.id).maybeSingle();if(!data){await supabase.auth.signOut();router.replace('/partner/login');return}setProfile(data);setLoading(false)};load()},[router]);const logout=async()=>{await supabase.auth.signOut();router.push('/partner/login')};if(loading)return <main className={styles.authWrap}><div className={styles.statusCard}>상태를 확인하고 있습니다.</div></main>;return <main className={styles.authWrap}><div className={styles.statusCard}><span className={styles.statusBadge}>{labels[profile.status]}</span><h1>{profile.status==='approved'?'파트너 승인이 완료되었습니다.':'파트너 신청이 접수되었습니다.'}</h1><p>사업자등록증 사본과 업체 홈페이지 또는 주로 활동하는 SNS 주소를 <a href="mailto:novelstudylab@naver.com">novelstudylab@naver.com</a>으로 보내주세요.</p><div className={styles.notice}>메일 제목:<br/><strong>[마이티북스 제휴 신청] {profile.business_name} / {profile.email}</strong><br/><br/>제출 자료를 확인한 뒤 승인 결과를 안내해드립니다.</div>{profile.status==='rejected'&&profile.rejected_reason&&<div className={styles.error}>안내 사유: {profile.rejected_reason}</div>}{profile.status==='suspended'&&<div className={styles.error}>현재 제휴가 중지된 상태입니다. 자세한 내용은 마이티북스로 문의해 주세요.</div>}<div className={styles.actions}>{profile.status==='approved'&&<Link href="/partner/dashboard" className={styles.primary}>파트너 기본 화면으로</Link>}<button type="button" className={styles.secondary} onClick={logout}>로그아웃</button></div></div></main>}
