'use client'
import { useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import styles from '../partner.module.css'

const initialForm={businessName:'',contactName:'',email:'',password:'',phone:'',businessType:'',region:'',websiteUrl:'',snsUrl:'',introductionPlan:'',hasOfflineStore:false,canDisplayCards:false,canDisplayBanner:false,agreed:false}

export default function PartnerSignupForm(){
  const [form,setForm]=useState(initialForm);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState(false);const router=useRouter()
  const set=(key,value)=>setForm(current=>({...current,[key]:value}))
  const submit=async(event)=>{event.preventDefault();if(!form.agreed)return;if(!form.websiteUrl.trim()&&!form.snsUrl.trim()){setError('업체 홈페이지 또는 주로 활동하는 SNS 주소를 하나 이상 입력해 주세요.');return}setLoading(true);setError('');const {data,error:signUpError}=await supabase.auth.signUp({email:form.email,password:form.password,options:{data:{account_type:'partner',business_name:form.businessName,contact_name:form.contactName,phone:form.phone,business_type:form.businessType,region:form.region,website_url:form.websiteUrl,sns_url:form.snsUrl,introduction_plan:form.introductionPlan,has_offline_store:form.hasOfflineStore,can_display_cards:form.canDisplayCards,can_display_banner:form.canDisplayBanner}}});setLoading(false);if(signUpError){setError(signUpError.message.includes('registered')?'이미 가입된 이메일입니다.':'가입을 처리하지 못했습니다. 입력 내용을 확인해 주세요.');return}if(data.session){router.push('/partner/pending');router.refresh();return}setSuccess(true)}
  if(success)return <main className={styles.authWrap}><div className={styles.statusCard}><span className={styles.statusBadge}>이메일 확인 필요</span><h1>파트너 신청 계정을 확인해 주세요.</h1><p>가입 이메일로 전송된 확인 링크를 누른 뒤 로그인해 주세요. 로그인 후 사업자등록증 사본과 온라인 활동 주소 제출 방법을 다시 안내합니다.</p><div className={styles.actions}><Link href="/partner/login" className={styles.primary}>파트너 로그인</Link><Link href="/partner" className={styles.secondary}>안내 페이지로</Link></div></div></main>
  return <main className={styles.authWrap}><div className={styles.authBox}><span className={styles.eyebrow}>Partner Application</span><h1>사업자 파트너 회원가입</h1><p className={styles.authIntro}>일반 소비자용 회원가입이 아닙니다. 실제 사업을 운영하며 마이티북스 파트너십 심사를 신청하는 업체만 가입해 주세요.</p><form onSubmit={submit} className={styles.formGrid}>
    <div className={styles.field}><label>업체명</label><input className={styles.input} value={form.businessName} onChange={e=>set('businessName',e.target.value)} required/></div><div className={styles.field}><label>담당자명</label><input className={styles.input} value={form.contactName} onChange={e=>set('contactName',e.target.value)} required/></div>
    <div className={styles.field}><label>로그인 이메일</label><input className={styles.input} type="email" value={form.email} onChange={e=>set('email',e.target.value)} required/></div><div className={styles.field}><label>비밀번호</label><input className={styles.input} type="password" minLength={8} value={form.password} onChange={e=>set('password',e.target.value)} required/></div>
    <div className={styles.field}><label>연락처</label><input className={styles.input} type="tel" value={form.phone} onChange={e=>set('phone',e.target.value)} required/></div><div className={styles.field}><label>업종</label><input className={styles.input} placeholder="예: 꽃집, 답례품" value={form.businessType} onChange={e=>set('businessType',e.target.value)} required/></div>
    <div className={styles.field}><label>활동 지역</label><input className={styles.input} value={form.region} onChange={e=>set('region',e.target.value)} required/></div><div className={styles.field}><label>홈페이지 주소</label><input className={styles.input} type="url" value={form.websiteUrl} onChange={e=>set('websiteUrl',e.target.value)}/></div>
    <div className={`${styles.field} ${styles.fieldFull}`}><label>SNS·네이버 플레이스·블로그 주소</label><input className={styles.input} type="url" value={form.snsUrl} onChange={e=>set('snsUrl',e.target.value)}/></div>
    <div className={`${styles.field} ${styles.fieldFull}`}><label>마이티북스의 제휴 혜택을 어떤 고객에게, 어떤 상황에서 안내할 계획인지 적어주세요.</label><textarea className={styles.textarea} value={form.introductionPlan} onChange={e=>set('introductionPlan',e.target.value)} required/></div>
    <div className={`${styles.checks} ${styles.fieldFull}`}><label className={styles.check}><input type="checkbox" checked={form.hasOfflineStore} onChange={e=>set('hasOfflineStore',e.target.checked)}/>오프라인 매장을 운영합니다.</label><label className={styles.check}><input type="checkbox" checked={form.canDisplayCards} onChange={e=>set('canDisplayCards',e.target.checked)}/>고객용 안내 카드를 비치할 수 있습니다.</label><label className={styles.check}><input type="checkbox" checked={form.canDisplayBanner} onChange={e=>set('canDisplayBanner',e.target.checked)}/>협의 후 미니 배너를 비치할 수 있습니다.</label><label className={styles.check}><input type="checkbox" checked={form.agreed} onChange={e=>set('agreed',e.target.checked)} required/>파트너 심사를 위해 입력한 업체·담당자·연락처 정보를 수집하고 검토하는 데 동의합니다.</label></div>
    {error&&<div className={`${styles.error} ${styles.fieldFull}`} role="alert">{error}</div>}<div className={styles.fieldFull}><button className={styles.submit} disabled={loading||!form.agreed}>{loading?'신청 중…':'파트너십 신청하기'}</button></div>
  </form><p className={styles.authFooter}>이미 신청하셨나요? <Link href="/partner/login" className={styles.textLink}>파트너 로그인</Link></p></div></main>
}
